// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAeyb7Q-tXi1L8RJeK4nW5GIzT7TEFI05U",
    authDomain: "myapp-289e9.firebaseapp.com",
    projectId: "myapp-289e9",
    storageBucket: "myapp-289e9.appspot.com",
    messagingSenderId: "1051779842971",
    appId: "1:1051779842971:web:7c0ff5e1be642ea278173e",
    measurementId: "G-DLBZP5YM98",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB0A9ZABGP9VOZ-OcNreIjF31BtpBeWyY',
    appId: '1:1051779842971:android:95953266a541c41478173e',
    messagingSenderId: '1051779842971',
    projectId: 'myapp-289e9',
    storageBucket: 'myapp-289e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwUfOvjD2WsvUIAiA8MfCrsRx7OSZkqZQ',
    appId: '1:1051779842971:ios:940638b2b51f3db678173e',
    messagingSenderId: '1051779842971',
    projectId: 'myapp-289e9',
    storageBucket: 'myapp-289e9.appspot.com',
    iosClientId:
        '1051779842971-a7udpqj0jo1jbpolmlv6ilff9ah5594t.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwUfOvjD2WsvUIAiA8MfCrsRx7OSZkqZQ',
    appId: '1:1051779842971:ios:940638b2b51f3db678173e',
    messagingSenderId: '1051779842971',
    projectId: 'myapp-289e9',
    storageBucket: 'myapp-289e9.appspot.com',
    iosClientId:
        '1051779842971-a7udpqj0jo1jbpolmlv6ilff9ah5594t.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
